all: hello0 hello1 hello2 hello3

hello0: hello0.v
	iverilog -o hello0 hello0.v

hello1: hello1.v
	iverilog -o hello1 hello1.v

hello2: hello2.v
	iverilog -o hello2 hello2.v

hello3: hello3.v
	iverilog -o hello3 hello3.v

clean:
	rm -f a.out hello0 hello1 hello2 hello3

